name: CityLifeFriends
version: 1.0-SNAPSHOT
main: org.serverct.sir.citylifefriends.CityLifeFriends
depend: [CityLifeCore]
commands:
  citylifefriends:
    aliases:
      - clf
      - clfriend
      - clfriends
