Hooks:
  Vault: true
  PlaceholdersAPI: false
Effect:
  Enable: true
  Success: HAPPY_VILLAGER
  Failure: VILLAGER_THUNDERCLOUD
Sound:
  Enable: true
  Success: LEVEL_UP
  Failure: ANVIL_BREAK
Economy:
  Punch: 100
  Absorb: 100
Attributes:
  VAMPIRE_RATE:
    Enable: true
    Display: "吸血几率"
    Color: RED
  VAMPIRE_PERCENT:
    Enable: true
    Display: "吸血回复"
    Color: GREEN
  CRITICAL_RATE:
    Enable: true
    Display: "暴击几率"
    Color: GOLD
  CRITICAL_DAMAGE:
    Enable: true
    Display: "暴击伤害"
    Color: GOLD
  REGENERATION:
    Enable: true
    Display: "生命恢复"
    Color: RED
  PHYSICAL_DEFENSE:
    Enable: true
    Display: "物理防御"
    Color: BLUE
  NAUSEA:
    Enable: true
    Display: "反胃几率"
    Color: GRAY
    Duration: 5
  BURN:
    Enable: true
    Display: "点燃几率"
    Color: RED
  IMPRISONMENT:
    Enable: true
    Display: "禁锢几率"
    Color: DARK_GRAY
    Duration: 5
  HEALTH:
    Enable: true
    Display: "生命力"
    Color: RED