name: SoulRing
version: ${project.version}
main: org.serverct.sir.soulring.SoulRing
depend: [Vault]
authors: [EntityParrot_]
description: A custom RPG plugin, idea from Douro.
commands:
  soulring:
    description: Plugin main command.
    usage: /<command>
    aliases: [sr, soulr, sring]