name: CityLifeFriends
version: ${project.version}
main: org.serverct.sir.citylifefriends.CityLifeFriends
depend: [CityLifeCore]
commands:
  citylifefriends:
    aliases:
      - clf
      - clfriend
      - clfriends
